version: "3.9"

services:
  db_test:
    image: postgres:latest
    volumes:
      - ./.db_volumes/org_test_db:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_DB=fin_test
      - POSTGRES_USER=fin_test_user
      - POSTGRES_PASSWORD=fin_test_pwd

  rabbitmq:
    image: rabbitmq:3.12.0-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test_user
      - RABBITMQ_DEFAULT_PASS=test_pwd
    ports:
      - 5672:5672
      - 15672:15672
